const fs = require('fs');
const path = require('path');
const https = require('https');

// Import environment config
const environmentPath = path.join(__dirname, 'chrome/environments/environment.ts');
const envContent = fs.readFileSync(environmentPath, 'utf8');

// Extract Firebase config from environment.ts
const databaseURLMatch = envContent.match(/databaseURL:\s*"([^"]+)"/);
if (!databaseURLMatch) {
  console.error('❌ Cannot find databaseURL in environment.ts');
  process.exit(1);
}

const DATABASE_URL = databaseURLMatch[1];
const ENVIRONMENT_NAME = 'VGCODER';

// Fixed IDs for Firebase
const FIXED_DOMAIN_ID = '3ceca557-71c7-43b6-8607-d03f7bc1b501';
const FIXED_SCRIPT_ID = '455ebef0-6ccc-461a-8e74-f76c8d59cfd1';

/**
 * Read all JavaScript files from a domain folder and concatenate them
 * @param {string} domainPath - Path to the domain folder
 * @param {string} domainName - Domain name for metadata
 * @returns {string} Concatenated code from all .js files with deployment header
 */
function concatenateScripts(domainPath, domainName) {
  const files = fs.readdirSync(domainPath);
  const jsFiles = files.filter(f => f.endsWith('.js')).sort();
  
  if (jsFiles.length === 0) {
    console.warn(`⚠️  No JavaScript files found in ${domainPath}`);
    return '';
  }
  
  console.log(`📄 Found ${jsFiles.length} JavaScript files: ${jsFiles.join(', ')}`);
  
  const contents = jsFiles.map(file => {
    const filePath = path.join(domainPath, file);
    const content = fs.readFileSync(filePath, 'utf8');
    console.log(`  ✓ Read ${file} (${content.length} bytes)`);
    return content;
  });
  
  const code = contents.join('\n\n');
  
  // Add deployment metadata header
  const now = new Date();
  const version = now.toISOString().replace(/[:.]/g, '-').split('T')[0] + '_' + now.getTime();
  const header = `/*********************************
 * AUTO-DEPLOYED SCRIPT
 * 
 * Domain: ${domainName}
 * Version: ${version}
 * Deployed: ${now.toISOString()}
 * Files: ${jsFiles.join(', ')}
 * 
 * Generated by: deploy-scripts.js
 * Environment: ${ENVIRONMENT_NAME}
 *********************************/\n\n`;
  
  return header + code;
}

/**
 * Get all domain folders from scripts directory
 * @returns {Array<{name: string, path: string}>} Array of domain folders
 */
function getDomainFolders() {
  const scriptsDir = path.join(__dirname, 'scripts');
  const entries = fs.readdirSync(scriptsDir, { withFileTypes: true });
  
  return entries
    .filter(entry => entry.isDirectory())
    .map(entry => ({
      name: entry.name,
      path: path.join(scriptsDir, entry.name)
    }));
}

/**
 * Create the Firebase payload with fixed structure
 * @param {string} domain - Domain name (e.g., 'aistudio.google.com')
 * @param {string} code - Concatenated JavaScript code
 * @returns {object} Firebase payload
 */
function createPayload(domain, code) {
  const now = Date.now();
  
  return {
    deleted: false,
    domain: {
      [FIXED_DOMAIN_ID]: {
        actionType: "MAIN",
        deleted: false,
        domain: domain,
        id: FIXED_DOMAIN_ID,
        seqNo: now
      }
    },
    id: ENVIRONMENT_NAME,
    script: {
      [FIXED_SCRIPT_ID]: {
        actionType: "MAIN",
        code: code,
        deleted: false,
        domain: domain,
        id: FIXED_SCRIPT_ID,
        seqNo: now
      }
    },
    seqNo: now,
    sync: true
  };
}


/**
 * Push payload to Firebase via HTTP PUT request
 * @param {string} domain - Domain name
 * @param {object} payload - Firebase payload
 * @returns {Promise<void>}
 */
function pushToFirebase(domain, payload) {
  return new Promise((resolve, reject) => {
    // Parse Firebase URL
    const url = new URL(DATABASE_URL);
    const pathPrefix = url.pathname.replace(/\/$/, ''); // Remove trailing slash
    const targetPath = `${pathPrefix}/ENV/${ENVIRONMENT_NAME}.json`;
    
    const data = JSON.stringify(payload);
    
    const options = {
      hostname: url.hostname,
      port: 443,
      path: targetPath,
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(data)
      }
    };
    
    console.log(`\n🚀 Pushing to Firebase...`);
    console.log(`   URL: https://${options.hostname}${targetPath}`);
    console.log(`   Method: ${options.method}`);
    console.log(`   Domain: ${domain}`);
    console.log(`   Payload size: ${data.length} bytes`);
    
    const req = https.request(options, (res) => {
      let responseData = '';
      
      res.on('data', (chunk) => {
        responseData += chunk;
      });
      
      res.on('end', () => {
        if (res.statusCode >= 200 && res.statusCode < 300) {
          console.log(`✅ Successfully deployed to Firebase!`);
          console.log(`   Status: ${res.statusCode}`);
          console.log(`   Response: ${responseData.substring(0, 200)}${responseData.length > 200 ? '...' : ''}`);
          resolve();
        } else {
          console.error(`❌ Firebase request failed with status ${res.statusCode}`);
          console.error(`   Response: ${responseData}`);
          reject(new Error(`HTTP ${res.statusCode}: ${responseData}`));
        }
      });
    });
    
    req.on('error', (error) => {
      console.error('❌ HTTP request error:', error.message);
      reject(error);
    });
    
    req.write(data);
    req.end();
  });
}

/**
 * Main deployment function
 */
async function deployScripts() {
  console.log('🔥 Firebase Script Deployment Tool');
  console.log('=====================================\n');
  
  const domains = getDomainFolders();
  
  if (domains.length === 0) {
    console.error('❌ No domain folders found in scripts directory');
    process.exit(1);
  }
  
  console.log(`📂 Found ${domains.length} domain(s): ${domains.map(d => d.name).join(', ')}\n`);
  
  // Process each domain
  for (const domain of domains) {
    console.log(`\n📦 Processing domain: ${domain.name}`);
    console.log('─'.repeat(50));
    
    try {
      // Step 1: Concatenate scripts
      const code = concatenateScripts(domain.path, domain.name);
      
      if (!code) {
        console.warn(`⚠️  Skipping ${domain.name} (no code found)`);
        continue;
      }
      
      // Step 2: Create payload
      const payload = createPayload(domain.name, code);
      console.log(`\n📋 Created payload for ${domain.name}`);
      console.log(`   Code length: ${code.length} characters`);
      console.log(`   Domains: ${Object.keys(payload.domain).length}`);
      console.log(`   Scripts: ${Object.keys(payload.script).length}`);
      
      // Step 3: Push to Firebase
      await pushToFirebase(domain.name, payload);
      
      console.log(`\n✨ ${domain.name} deployment completed successfully!`);
      
    } catch (error) {
      console.error(`\n❌ Failed to deploy ${domain.name}:`, error.message);
      process.exit(1);
    }
  }
  
  console.log('\n\n🎉 All scripts deployed successfully!');
  console.log('=====================================\n');
}

// Run deployment
deployScripts().catch(error => {
  console.error('\n💥 Deployment failed:', error);
  process.exit(1);
});
